tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "romkatv/powerlevel10k"
brew "awscli", link: false
brew "cask"
brew "curl"
brew "go"
brew "helm"
brew "jq"
brew "jsonnet-bundler"
brew "kind"
brew "kubernetes-cli"
brew "kustomize"
brew "mas"
brew "maven"
brew "nmap"
brew "node@12"
brew "openjdk@11"
brew "perl"
brew "tanka"
brew "terraform", link: false
brew "tmux"
brew "vim"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "cloudflare/cloudflare/cloudflared"
brew "fluxcd/tap/flux"
brew "romkatv/powerlevel10k/powerlevel10k"
cask "drawio"
cask "firefox"
cask "fork"
cask "google-chrome"
cask "iterm2"
cask "lens"
cask "ngrok"
cask "owasp-zap"
cask "postman"
cask "rectangle"
cask "slack"
cask "spotify"
cask "tableplus"
cask "virtualbox"
cask "visual-studio-code"
mas "Microsoft Remote Desktop", id: 1295203466
mas "Xcode", id: 497799835
